
# META YAML

{% set name = "emews-r-x" %}
# See README for version meanings:
{% set version = "6" %}

package:
  name:    {{ name }}
  version: {{ version }}

source:
  # R_SVN is exported by conda-build.sh
  path: {{ environ.get('R_SVN', 'UNSET_R_SVN') }}

build:
  number: 1
  # Environment variables for build.sh must be listed here,
  # normal environment inheritance does not happen!
  script_env:
    - PLATFORM={{ environ.get('PLATFORM', 'UNSET_PLATFORM') }}

# Remember to sync any dependency changes here with conda-install.sh
requirements:
  build:
    - libcurl
    - pcre2
    - xz
    - gfortran
    - zlib
    # For X11:
    # xorg-x11-proto-devel-cos6-x86_64
    - xorg-libx11 # xorg-x11-proto-devel
    - xorg-xorgproto
    - xorg-libxt  # For X11/Intrinsic.h
    - libiconv  # For iconv.h
    - cairo
    - clangxx

  run:
    - libcurl
    - pcre2
    - xz
    - gfortran
    - zlib
    # For X11:
    # xorg-x11-proto-devel-cos6-x86_64
    - xorg-libx11 # xorg-x11-proto-devel
    - xorg-xorgproto
    - xorg-libxt  # For X11/Intrinsic.h
    - libiconv  # For iconv.h
    - cairo

test:
  commands:
    - echo
    - echo "meta.yaml test commands:"
    - which R Rscript
    - R -e 'cat("R-SUCCESS:", 42, "\n")'

about:
  home: https://github.com/emews/emews-r-base
  license: Apache License 2.0
  summary: EMEWS build for R

extra:
  recipe-maintainers:
    - swift-t
