
= emews-r-x

A simple Anaconda package with unmodified R from SVN for use with EMEWS.

Only necessary for platform `osx-arm64`, due to a memory error in the official Anaconda release.  Still a problem as of 2024-12-12.

See the projects for `emews-r` and `emews-rinside`.

Remember to use `capabilities()` to check features.

Using R from SVN r85879 .

== User installation

The end user should be able to simply:

----
$ conda install -c swift-t emews-r-x
----

This will install R in the given Anaconda.

This should default to the latest version (see below).

The user can then run:

----
$ ./install-apps.sh
----

to install the "application" libraries `farver` and `ggplot2`.

== Versions for X and other features

Our original `emews-r` was built with:
----
--enable-R-shlib
--disable-java
--without-readline
--without-tcltk
--without-cairo
--without-jpeglib
--without-libtiff
--without-ICU
--with-included-gettext
--without-x
--without-recommended-packages
--without-aqua
----

This project tries to re-enable these features as needed for `ggplot2` and other graphical applications.

In priority order from top priority (1) to lowest:

emews-r-x==1::
Drops `--without-x`.       +
Works, tested by jozik .

emews-r-x==2::
Drops `--without-aqua`.       +
Uploaded, untested.

emews-r-x==3::
Drops `--without-readline`.    +
Uploaded, untested.

emews-r-x==4::
Drops `--without-cairo`.       +
Cairo seems to be important for plotting file formats. +

emews-r-x==5::
Force installation of `clangxx` to address issue when building packages with C++

emews-r-x==6::
+
. Move to R release tag 4.4.3 .
. Add `activate.sh` to address `.libPaths()` issue
. Added package `clangxx` at runtime
. Ready for testing

== Usage

. Install a build Miniconda
. Run `setup-conda.sh`
. Run `conda-build.sh`

== Notes

Remember to:
. Update PLATFORM
.. in conda-build.sh
.. in meta.yaml
. Update `meta.yaml:source:path:`
. Install xcrun

=== For SSH

. Use `ssh -X`
. Set `ForwardX11Trusted yes`

=== Interactive builds (for humans)

. Install a fresh Anaconda
. `$ ./human-setup.sh`
. `$ ./human-build.sh R_SVN WORK` +
where
`R_SVN` is the R SVN checkout and
`WORK` is a temporary build directory for R

== Troubleshooting

=== libxml errors

Reinstall conda- this is probably a Mac /tmp auto-delete issue
