#!/bin/bash
set -eu

# TEST BUILD
# Check logs from build step

echo "TEST-BUILD"

if ! [[ -f conda-build.log ]]
then
  echo "not found: conda-build.log!"
  exit 1
fi

MSG="CONDA-BUILD: SUCCESS"
if ! grep -q "${MSG}" conda-build.log
then
  echo "not found in conda-build.log: '$MSG'"
  echo
  echo "conda-build.log: START"
  cat   conda-build.log
  echo "conda-build.log: END"
  echo
  exit 1
fi

echo "TEST-BUILD: OK"
